### ISSUE TITLE
How to send otp on mobile number, rather than email.

### ISSUE THREAD

**Issue by Bearbobs** [101Loop/drf-user#73]
Currently when I register using otpreglogin/ endpoint, it sends otp for mobile as well as email to my email id :
![image](https://user-images.githubusercontent.com/21145870/95293657-7d46bc80-0891-11eb-9d27-e2f600bf1510.png)

I want it to be sent directly on the mobile number.
Thanks

**Comment by sumit4613** [comment]
@Bearbobs  If you use this format to send your data, then you'll be able to send a message on mobile as well.
```
data = {
        "recip_email": ["email_here", ],
        "subject": "subject",
        "message": "message",
        "recip": ["mobile_here", ],
    }
```
Currently it sends emails wether we require or not, i'll be fixing this soon so that it can be configured using settings.
If you know django and want to fix this then please raise a PR, would love to review. 
Thanks!

**Comment by Bearbobs** [comment]
@sumit4613  follow up question:
- Which SMS backend drf_users is using? would it not be good to have a settings config for the same

**Comment by sumit4613** [comment]
@Bearbobs We use [django-sendsms](https://github.com/stefanfoulis/django-sendsms) to send sms, you can create your custom sms backend in `django-sendsms` using any third-party API.

**Comment by Bearbobs** [comment]
Thanks,

**Comment by sumit4613** [comment]
@Bearbobs I hope this resolves your query, closing this issue for now. If you have further queries, please create separate issue for them. 
Thanks!
